# For info on multiline regular expressions: https://pre-commit.com/index.html#regular-expressions
# Verbose regular expressions '(?x)': https://docs.python.org/3.9/library/re.html#re.X
exclude: |
  (?x)^(
      .idea/|
      .venv/
      # add more directories here
      #|dir/
      ).*$
default_install_hook_types: [pre-commit, pre-merge-commit, pre-push]
default_stages: [pre-commit, pre-merge-commit, pre-push, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.2
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17 # Use the ref you want to point at
    hooks:
      - id: mdformat
        name: mdformat on non-.github files
        exclude: ^.github/
        args: ["--wrap", "80", "--number"]
        # Optionally add plugins
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter
          - mdformat-footnote
          - mdformat-toc
      - id: mdformat
        name: mdformat on .github files
        files: ^.github/.*$
        # Don't wrap the templates in .github; they don't look good in the description
        args: ["--wrap", "no", "--number"]
        # Optionally add plugins
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter
          - mdformat-footnote
          - mdformat-toc
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.2
    hooks:
      - id: hadolint
        # Ignored warnings:
        # DL3041 warning: Specify version with `dnf install -y <package>-<version>`
        args: [--ignore, DL3041]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        # -x: Follow source statements
        args: [-x]
  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v3.7.0.1
    hooks:
      - id: shfmt
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.289
    hooks:
      - id: ruff
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        stages: [manual]
        name: mypy (CI)
        additional_dependencies:
          # Add dependencies that have type data here.
          # At least include the AWS libraries that are in
          # requirements.txt
          - aws-cdk-lib==2.88.0
          - constructs>=10.0.0,<11.0.0
  - repo: local
    hooks:
      - id: dmypy
        stages: [pre-commit, pre-merge-commit, push]
        name: dmypy (for pre-commit, merge, push)
        entry: pdm
        types: [python]
        language: system
        require_serial: true
        # config and actual args for dmypy is in pyproject.toml
        args: ["run", "mypy"]
