name: pre-commit

on:
  pull_request:
  push:
    branches: [develop, python]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/cache@v3
        with:
          path: .mypy_cache
          key: mypy_cache|${{ hashFiles('pyproject.toml') }}
      - uses: datalogics/pre-commit-github-action@v3.0.0
        with:
          extra_args: "--all-files --hook-stage manual"
